### ISSUE TITLE
Installation fails on node 12

### ISSUE THREAD

**Issue by stheine** [TooTallNate/node-ogg#26]
Installation on `node 12` fails with:

```
> ogg@1.2.6 install /app/node_modules/ogg
> node-gyp rebuild

make: Entering directory '/app/node_modules/ogg/build'
  CC(target) Release/obj.target/libogg/deps/libogg/src/framing.o
  CC(target) Release/obj.target/libogg/deps/libogg/src/bitwise.o
  AR(target) Release/obj.target/deps/libogg/ogg.a
  COPY Release/ogg.a
  CXX(target) Release/obj.target/ogg/src/binding.o
../src/binding.cc: In member function ‘virtual void nodeogg::OggSyncWriteWorker::HandleOKCallback()’:
../src/binding.cc:62:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(1, argv);
                           ^
In file included from ../src/binding.cc:23:0:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE nodeogg::node_ogg_sync_write(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cc:76:54: error: no matching function for call to ‘v8::Value::NumberValue()’
   long size = static_cast<long>(info[2]->NumberValue());
                                                      ^
In file included from /root/.cache/node-gyp/12.13.1/include/node/node.h:63:0,
                 from ../src/binding.cc:22:
/root/.cache/node-gyp/12.13.1/include/node/v8.h:2608:39: note: candidate: v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
                                       ^~~~~~~~~~~
/root/.cache/node-gyp/12.13.1/include/node/v8.h:2608:39: note:   candidate expects 1 argument, 0 provided
../src/binding.cc: In member function ‘virtual void nodeogg::OggSyncPageoutWorker::HandleOKCallback( ’:
../src/binding.cc:105:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(3, argv);
                           ^
In file included from ../src/binding.cc:23:0:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE nodeogg::node_ogg_stream_init(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cc:128:57: error: no matching function for call to ‘v8::Value::IntegerValue()’
   int serialno = static_cast<int>(info[1]->IntegerValue());
                                                         ^
In file included from /root/.cache/node-gyp/12.13.1/include/node/node.h:63:0,
                 from ../src/binding.cc:22:
/root/.cache/node-gyp/12.13.1/include/node/v8.h:2609:40: note: candidate: v8::Maybe<long long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^~~~~~~~~~~~
/root/.cache/node-gyp/12.13.1/include/node/v8.h:2609:40: note:   candidate expects 1 argument, 0 provided
../src/binding.cc: In member function ‘virtual void nodeogg::OggStreamPageinWorker::HandleOKCallback()’:
../src/binding.cc:146:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(1, argv);
                           ^
In file included from ../src/binding.cc:23:0:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/binding.cc: In member function ‘virtual void nodeogg::OggStreamPacketoutWorker::HandleOKCallback()’:
../src/binding.cc:193:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(6, argv);
                           ^
In file included from ../src/binding.cc:23:0:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/binding.cc: In member function ‘virtual void nodeogg::OggStreamPacketinWorker::HandleOKCallback()’:
../src/binding.cc:226:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(1, argv);
                           ^
In file included from ../src/binding.cc:23:0:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/binding.cc: In member function ‘virtual void nodeogg::StreamWorker::HandleOKCallback()’:
../src/binding.cc:267:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(4, argv);
                           ^
In file included from ../src/binding.cc:23:0:
../../nan/nan.h:1740:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/binding.cc: In function ‘void nodeogg::Initialize(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/binding.cc:404:8: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
   Nan::ForceSet(target, Nan::New<String>("sizeof_" #value).ToLocalChecked(), \
        ^
../src/binding.cc:407:3: note: in expansion of macro ‘SIZEOF’
   SIZEOF(ogg_sync_state);
   ^~~~~~
In file included from ../../nan/nan.h:282:0,
                 from ../src/binding.cc:23:
../../nan/nan_maybe_43_inl.h:117:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^~~~~~~~
../src/binding.cc:406:58: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
       static_cast<PropertyAttribute>(ReadOnly|DontDelete))
                                                          ^
../src/binding.cc:407:3: note: in expansion of macro ‘SIZEOF’
   SIZEOF(ogg_sync_state);
   ^~~~~~
In file included from ../../nan/nan.h:282:0,
                 from ../src/binding.cc:23:
../../nan/nan_maybe_43_inl.h:117:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^~~~~~~~
../src/binding.cc:404:8: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
   Nan::ForceSet(target, Nan::New<String>("sizeof_" #value).ToLocalChecked(), \
        ^
../src/binding.cc:408:3: note: in expansion of macro ‘SIZEOF’
   SIZEOF(ogg_stream_state);
   ^~~~~~
In file included from ../../nan/nan.h:282:0,
                 from ../src/binding.cc:23:
../../nan/nan_maybe_43_inl.h:117:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^~~~~~~~
../src/binding.cc:406:58: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
       static_cast<PropertyAttribute>(ReadOnly|DontDelete))
                                                          ^
../src/binding.cc:408:3: note: in expansion of macro ‘SIZEOF’
   SIZEOF(ogg_stream_state);
   ^~~~~~
In file included from ../../nan/nan.h:282:0,
                 from ../src/binding.cc:23:
../../nan/nan_maybe_43_inl.h:117:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^~~~~~~~
../src/binding.cc:404:8: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
   Nan::ForceSet(target, Nan::New<String>("sizeof_" #value).ToLocalChecked(), \
        ^
../src/binding.cc:409:3: note: in expansion of macro ‘SIZEOF’
   SIZEOF(ogg_page);
   ^~~~~~
In file included from ../../nan/nan.h:282:0,
                 from ../src/binding.cc:23:
../../nan/nan_maybe_43_inl.h:117:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^~~~~~~~
../src/binding.cc:406:58: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
       static_cast<PropertyAttribute>(ReadOnly|DontDelete))
                                                          ^
../src/binding.cc:409:3: note: in expansion of macro ‘SIZEOF’
   SIZEOF(ogg_page);
   ^~~~~~
In file included from ../../nan/nan.h:282:0,
                 from ../src/binding.cc:23:
../../nan/nan_maybe_43_inl.h:117:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^~~~~~~~
../src/binding.cc:404:8: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
   Nan::ForceSet(target, Nan::New<String>("sizeof_" #value).ToLocalChecked(), \
        ^
../src/binding.cc:410:3: note: in expansion of macro ‘SIZEOF’
   SIZEOF(ogg_packet);
   ^~~~~~
In file included from ../../nan/nan.h:282:0,
                 from ../src/binding.cc:23:
../../nan/nan_maybe_43_inl.h:117:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^~~~~~~~
../src/binding.cc:406:58: warning: ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’ is deprecated [-Wdeprecated-declarations]
       static_cast<PropertyAttribute>(ReadOnly|DontDelete))
                                                          ^
../src/binding.cc:410:3: note: in expansion of macro ‘SIZEOF’
   SIZEOF(ogg_packet);
   ^~~~~~
In file included from ../../nan/nan.h:282:0,
                 from ../src/binding.cc:23:
../../nan/nan_maybe_43_inl.h:117:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^~~~~~~~
../src/binding.cc:434:77: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
     Nan::New<FunctionTemplate>(node_ogg_packet_replace_buffer)->GetFunction());
                                                                             ^
In file included from /root/.cache/node-gyp/12.13.1/include/node/node.h:63:0,
                 from ../src/binding.cc:22:
/root/.cache/node-gyp/12.13.1/include/node/v8.h:5995:46: note: candidate: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/root/.cache/node-gyp/12.13.1/include/node/v8.h:5995:46: note:   candidate expects 1 argument, 0 provided
ogg.target.mk:114: recipe for target 'Release/obj.target/ogg/src/binding.o' failed
make: *** [Release/obj.target/ogg/src/binding.o] Error 1
make: Leaving directory '/app/node_modules/ogg/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.66-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/ogg
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN wecker@0.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ogg@1.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ogg@1.2.6 install script.
```

**Comment by renanyoy** [comment]
please add a fix, nodejs 10 isn't supported anymore...

**Comment by ifxsoftware** [comment]
really wish there was another ogg page this one hasnt worked for year now
